name: peoples-preferences
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - flake8=6.0.0
    - snakemake-minimal=7.25.0
    - pycountry=22.3.5
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
