name: peoples-preferences
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.10
    - flake8=3.8.3
    - snakemake-minimal=7.8.1
variables:
    SNAKEMAKE_PROFILE: ./profiles/default
