data-sources:
    conjointly: data/raw-data-{country_id}.csv
    respondi: data/respondi/Masterdata_14979_{country_id}.xlsx
cluster-sync:
    url: euler.ethz.ch
    send-ignore: .syncignore-send
    receive-ignore: .syncignore-receive
    cluster-base-dir: ~/Develop/peoples-preferences
    local-results-dir: build/cluster
data-types:
    RESPONDENT_ID:
        type: factor
        ordered: False
    CHOICE_SET:
        type: factor
        ordered: True
    LABEL:
        type: factor
        ordered: True
        rename:
            1: Left
            2: Right
    TECHNOLOGY:
        type: factor
        ordered: False
        relevel:
            - Rooftop PV
            - Open-field PV
            - Wind
    SHARE_IMPORTS:
        type: factor
        ordered: False
    LAND:
        type: factor
        ordered: False
    PRICES:
        type: factor
        ordered: False
    TRANSMISSION:
        type: factor
        ordered: False
        relevel:
            - -25%
            - +0%
            - +25%
            - +50%
            - +75%
        rename:
            "-25%": "-25.0% ."
            "+0%": "+0% ."
            "+25%": "+25% ."
            "+50%": "+50% ."
            "+75%": "+75% ."
    OWNERSHIP:
        type: factor
        ordered: False
        relevel:
            - Public
            - Community
            - Private
    RESPONDENT_COUNTRY:
        type: factor
        ordered: False
    RESPONDENT_DEVICE_USED_IN_SURVEY:
        type: factor
        ordered: False
    Q2_AGE_TRESHOLD:
        type: factor
        ordered: False
        rename:
            0: Below
            1: Above
    Q3_GENDER:
        type: factor
        ordered: False
        rename:
            1: Female
            2: Male
            3: Other
    Q4_BIRTH_YEAR:
        type: numeric
        min: 1922 # max 100 years old
        max: 2004 # min 18 years old
    Q6_AREA:
        type: factor
        ordered: False
        missing-values: [3]
        rename:
            1: Rural
            2: Urban
    Q7_RENEWABLES:
        type: factor
        ordered: False
        missing-values: [5]
        rename:
            1: Open-field PV
            2: Wind
            3: Both
            4: Neither
    Q8_YEARS_REGION:
        type: numeric
        min: 0
        max: 100
    Q9_EDUCATION:
        type: factor
        ordered: True
        missing-values: [7, 8] # ASSUME "other" irrelevant (~2.66% of respondents)
        rename:
            1: None
            2: None but in eduction
            3: Vocational
            4: Master craftsman
            5: Bachelor or Master
            6: Doctor
    Q10_INCOME:
        type: factor
        ordered: True
        missing-values: [12]
        rename:
            1: Below 600 EUR
            2: 600--900 EUR
            3: 900--1300 EU
            4: 1300--1500 EU
            5: 1500--2000 EUR
            6: 2000--2600 EUR
            7: 2600--3200 EUR
            8: 3200--4500 EUR
            9: 4500--6000 EUR
            10: 6000--10000 EUR
            11: Above 10000 EUR
    Q11_CLIMATE_CONCERN:
        type: factor
        ordered: True
        missing-values: [6, 7]
        rename:
            1: Not at all
            2: Not much
            3: Somewhat
            4: Very
            5: Extremely
    Q12_PARTY:
        type: factor
        ordered: False
        missing-values: [8, 21, 33, 46]
        rename:
            1: CDU / CSU
            2: SPD
            3: Bündnis 90 / Die Grünen
            4: Die Linke
            5: AfD
            6: FDP
            7: Other (DEU)
            9: Det Konservative Folkeparti (KF)
            10: Socialdemokratiet i Danmark (S)
            11: Alternativet (A)
            12: Venstre, Danmarks Liberale Parti (V)
            13: Dansk Folkeparti (DF)
            14: Socialistisk Folkeparti (SF)
            15: Enhedslisten - De Rød-Grønne (EL)
            16: Det Radikale Venstre (RV)
            17: Nye Borgerlige (NB)
            18: Liberal Alliance (LA)
            19: Kristendemokraterne (KD)
            20: Other (DNK)
            22: Platforma Obywatelska (PO)
            23: Polskie Stronnictwo Ludowe (PSL)
            24: Prawo i Sprawiedliwość (PiS)
            25: Nowoczesna (N)
            26: Sojusz Lewicy Demokratycznej (SLD)
            27: Konfederacja Wolność i Niepodległość (KONFEDERACJA)
            28: Mniejszość Niemiecka (MN)
            29: Kukiz'15 (K)
            30: Razem, Nowa Lewica
            31: Partia Zieloni
            32: Other (POL)
            34: Partido Socialista (PS)
            35: Partido Social Democrata (PSD)
            36: Bloco de Esquerda (BE)
            37: Coligação Democrática Unitária (CDU)
            38: Partido Comunista Português (PCP)
            39: Partido Ecologista 'Os Verdes' (PEV)
            40: Partido Popular (CDS-PP)
            41: Pessoas-Animais-Natureza (PAN)
            42: Chega (CH)
            43: Iniciativa Liberal (IL)
            44: Livre (L)
            45: Other (PRT)
    Q15_ATTRIBUTE_IMPORTANCE_O1:
        type: factor
        ordered: True
        rename:
            1: No agreement
            2: Low agreement
            3: Moderate agreement
            4: High agreement
            5: Very high agreement
    Q15_ATTRIBUTE_IMPORTANCE_O2:
        type: factor
        ordered: True
        rename:
            1: No agreement
            2: Low agreement
            3: Moderate agreement
            4: High agreement
            5: Very high agreement
    Q15_ATTRIBUTE_IMPORTANCE_O3:
        type: factor
        ordered: True
        rename:
            1: No agreement
            2: Low agreement
            3: Moderate agreement
            4: High agreement
            5: Very high agreement
    Q15_ATTRIBUTE_IMPORTANCE_O4:
        type: factor
        ordered: True
        rename:
            1: No agreement
            2: Low agreement
            3: Moderate agreement
            4: High agreement
            5: Very high agreement
    Q17_ORIGIN_COUNTRY:
        type: likert
    Q18_ORIGIN_EU:
        type: likert
    Q20_TRANSITION:
        type: likert
    Q21_ENVIRONMENTAL:
        type: likert
    Q22_CLIMATE_PROTECTION:
        type: likert
    Q23_DEMOCRATISATION:
        type: likert
    Q24_RESOURCES:
        type: likert
    Q25_DEPLOYMENT:
        type: likert
new-features:
    aggregated-levels:
        Q9_EDUCATION:
            ordered:
                - Lower
                - Higher
            mapping:
                "None":                 Lower
                "None but in eduction": Lower
                "Vocational":           Lower
                "Master craftsman":     Higher
                "Bachelor or Master":   Higher
                "Doctor":               Higher
        Q10_INCOME:
            ordered:
                - Low (<1500 EUR)
                - Middle (1500--4500 EUR)
                - High (>4500 EUR)
            mapping:
                "Below 600 EUR":    Low (<1500 EUR)
                "600--900 EUR":     Low (<1500 EUR)
                "900--1300 EU":     Low (<1500 EUR)
                "1300--1500 EU":    Low (<1500 EUR)
                "1500--2000 EUR":   Middle (1500--4500 EUR)
                "2000--2600 EUR":   Middle (1500--4500 EUR)
                "2600--3200 EUR":   Middle (1500--4500 EUR)
                "3200--4500 EUR":   Middle (1500--4500 EUR)
                "4500--6000 EUR":   High (>4500 EUR)
                "6000--10000 EUR":  High (>4500 EUR)
                "Above 10000 EUR":  High (>4500 EUR)
        Q11_CLIMATE_CONCERN:
            ordered:
                - Low
                - High
            mapping:
                "Not at all":   Low
                "Not much":     Low
                "Somewhat":     Low
                "Very":         High
                "Extremely":    High
        Q12_PARTY:
            mapping:
                "CDU / CSU":                                            Other
                "SPD":                                                  Other
                "Bündnis 90 / Die Grünen":                              Green
                "Die Linke":                                            Other
                "AfD":                                                  Right
                "FDP":                                                  Other
                "Other (DEU)":                                          Other
                "Det Konservative Folkeparti (KF)":                     Other
                "Socialdemokratiet i Danmark (S)":                      Other
                "Alternativet (A)":                                     Green
                "Venstre, Danmarks Liberale Parti (V)":                 Other
                "Dansk Folkeparti (DF)":                                Right
                "Socialistisk Folkeparti (SF)":                         Green
                "Enhedslisten - De Rød-Grønne (EL)":                    Green
                "Det Radikale Venstre (RV)":                            Other
                "Nye Borgerlige (NB)":                                  Right
                "Liberal Alliance (LA)":                                Other
                "Kristendemokraterne (KD)":                             Other
                "Other (DNK)":                                          Other
                "Platforma Obywatelska (PO)":                           Other
                "Polskie Stronnictwo Ludowe (PSL)":                     Other
                "Prawo i Sprawiedliwość (PiS)":                         Right
                "Nowoczesna (N)":                                       Other
                "Sojusz Lewicy Demokratycznej (SLD)":                   Other
                "Konfederacja Wolność i Niepodległość (KONFEDERACJA)":  Right
                "Mniejszość Niemiecka (MN)":                            Other
                "Kukiz'15 (K)":                                         Right
                "Razem, Nowa Lewica":                                   Other
                "Partia Zieloni":                                       Green
                "Other (POL)":                                          Other
                "Partido Socialista (PS)":                              Other
                "Partido Social Democrata (PSD)":                       Other
                "Bloco de Esquerda (BE)":                               Other
                "Coligação Democrática Unitária (CDU)":                 Other
                "Partido Comunista Português (PCP)":                    Other
                "Partido Ecologista 'Os Verdes' (PEV)":                 Green
                "Partido Popular (CDS-PP)":                             Right
                "Pessoas-Animais-Natureza (PAN)":                       Green
                "Chega (CH)":                                           Right
                "Iniciativa Liberal (IL)":                              Other
                "Livre (L)":                                            Green
                "Other (PRT)":                                          Other
    categorised-levels:
        Q4_BIRTH_YEAR:
            bins:
                - 1922
                - 1967
                - 1992
                - 2004
            labels:
                - Old
                - Middle
                - Young
            ordered:
                - Young
                - Middle
                - Old
        Q8_YEARS_REGION:
            bins:
                - 0
                - 5
                - 10
                - 15
                - 100
            labels:
                - Low
                - Medium
                - Strong
                - Very strong
            ordered:
                - Low
                - Medium
                - Strong
                - Very strong
clustering:
    4-with-country:
        features:
            - Q3_GENDER
            - Q4_BIRTH_YEAR
            - Q6_AREA
            - Q7_RENEWABLES
            - Q8_YEARS_REGION
            - Q9_EDUCATION
            - Q10_INCOME
            - Q11_CLIMATE_CONCERN
            - Q12_PARTY_aggregated
            - RESPONDENT_COUNTRY
        n-cluster: 4
    4-without-countries:
        features:
            - Q3_GENDER
            - Q4_BIRTH_YEAR
            - Q6_AREA
            - Q7_RENEWABLES
            - Q8_YEARS_REGION
            - Q9_EDUCATION
            - Q10_INCOME
            - Q11_CLIMATE_CONCERN
            - Q12_PARTY_aggregated
        n-cluster: 4
    16-with-country:
        features:
            - Q3_GENDER
            - Q4_BIRTH_YEAR
            - Q6_AREA
            - Q7_RENEWABLES
            - Q8_YEARS_REGION
            - Q9_EDUCATION
            - Q10_INCOME
            - Q11_CLIMATE_CONCERN
            - Q12_PARTY_aggregated
            - RESPONDENT_COUNTRY
        n-cluster: 16
parameters:
    population-count: # 2020, Source: https://data.worldbank.org/indicator/SP.POP.TOTL
        DEU: 83240525
        DNK: 5831404
        POL: 37950802
        PRT: 10305564
    pre-test-threshold: 2022-01-24 00:00
    Q12-party-base: # the smallest code used in the Q12-Party attribute (see `codes/Q12-Party` above)
        DEU: 1
        DNK: 9
        POL: 22
        PRT: 34
models:
    modelA:
        formula: ~ TECHNOLOGY + LAND + SHARE_IMPORTS + PRICES + OWNERSHIP # FIXME add transmission
        n-iterations: 5000
        burn-in-length: 2500
        keep: 1
    multinomial:
        n-tune: 1000
        n-draws: 1000
        limit-respondents: 200
        random-seed: 4000
    hierarchical-nocovariates:
        n-tune: 2000
        n-draws: 500
        limit-respondents: 80
        random-seed: 4000
        individual-covariates: False
    hierarchical-covariates:
        n-tune: 2000
        n-draws: 500
        limit-respondents: 80
        random-seed: 4000
        individual-covariates: True
report:
    hdi_prob: 0.94
