# The right place for all your configuration values.
data-sources:
    conjointly: data/raw-data-{country_id}.csv
    respondi: data/respondi/Masterdata_14979_{country_id}.xlsx
codes:
    Q3_GENDER:
        1: female
        2: male
        3: other
    Q6_AREA:
        1: rural
        2: urban
        3: no answer
    Q10_INCOME:
        1: below 600 EUR
        2: 600--900 EUR
        3: 900--1300 EU
        4: 1300--1500 EU
        5: 1500--2000 EUR
        6: 2000--2600 EUR
        7: 2600--3200 EUR
        8: 3200--4500 EUR
        9: 4500--6000 EUR
        10: 6000--10000 EUR
        11: above 10000 EUR
        12: no answer
parameters:
    population-count: # 2020, Source: https://data.worldbank.org/indicator/SP.POP.TOTL
        DEU: 83240525
        DNK: 5831404
        POL: 37950802
        PRT: 10305564
    pre-test-threshold: 2022-01-24 00:00
