models:
    modelA:
        formula: ~ TECHNOLOGY + LAND + SHARE_IMPORTS + PRICES + TRANSMISSION + OWNERSHIP
        n-iterations: 150000
        burn-in-length: 100000
        keep: 10
    multinomial:
        n-tune: 2000
        n-draws: 2000
        limit-respondents: False
        random-seed: 4000
    hierarchical:
        n-tune: 4000
        n-draws: 2000
        limit-respondents: 2000 # FIXME do not limit
        random-seed: 4000
