models:
    modelA:
        formula: ~ TECHNOLOGY + LAND + SHARE_IMPORTS + PRICES + TRANSMISSION + OWNERSHIP
        n-iterations: 150000
        burn-in-length: 100000
        keep: 10
    hierarchical:
        n-respondents: 1000
