models:
    modelA:
        formula: ~ TECHNOLOGY + LAND + SHARE_IMPORTS + PRICES + TRANSMISSION + OWNERSHIP
        n-iterations: 150000
        burn-in-length: 100000
        keep: 10
    multinomial:
        n-tune: 2000
        n-draws: 2000
        limit-respondents: False
        random-seed: 4000
    hierarchical-nocovariates:
        n-tune: 10000
        n-draws: 3000
        limit-respondents: False
        random-seed: 4000
        individual-covariates: False
        runtime: 1440 # (min)
        memory: 96000 # (MB)
    hierarchical-covariates:
        n-tune: 10000
        n-draws: 2000
        limit-respondents: False
        random-seed: 4000
        individual-covariates: True
        runtime: 2880 # (min)
        memory: 320000 # (MB)
