parameters:
    synthetic-data:
        n-respondents: 4103
models:
    modelA:
        formula: ~ TECHNOLOGY + LAND + SHARE_IMPORTS + PRICES + TRANSMISSION + OWNERSHIP
        n-iterations: 150000
        burn-in-length: 100000
        keep: 10
    multinomial:
        n-tune: 2000
        n-draws: 2000
        limit-respondents: False
    hierarchical-nocovariates:
        n-tune: 10000
        n-draws:
            prior: 1000
            posterior: 3000
        limit-respondents: False
        runtime: # (min)
            prior: 60
            posterior: 1440
            prediction: 60
        mem_mb:
            prior: 48000
            posterior: 96000
            memory: 48000
    hierarchical-covariates:
        n-tune: 10000
        n-draws:
            prior: 1000
            posterior: 3000
        limit-respondents: False
        runtime: # (min)
            prior: 60
            posterior: 2880
            prediction: 60
        mem_mb:
            prior: 48000
            posterior: 320000
            memory: 48000
    hierarchical-nocovariates-nocovariances:
        n-tune: 3000
        n-draws:
            prior: 1000
            posterior: 3000
        limit-respondents: False
        runtime: # (min)
            prior: 60
            posterior: 2880
            prediction: 60
        mem_mb:
            prior: 48000
            posterior: 180000
            prediction: 48000
