models:
    multinomial:
        n-tune: 2000
        n-draws: 2000
        limit-respondents: False
        random-seed: 4000
    hierarchical-nocovariates:
        n-tune: 6000
        n-draws: 2000
        limit-respondents: 1000
        random-seed: 4000
        individual-covariates: False
        runtime: 720 # (min)
        mem_mb: 46000
    hierarchical-covariates:
        n-tune: 6000
        n-draws: 2000
        limit-respondents: 1000
        random-seed: 4000
        individual-covariates: True
        runtime: 1440 # (min)
        mem_mb: 96000
