parameters:
    synthetic-data:
        n-respondents: 1000
models:
    multinomial:
        n-tune: 2000
        n-draws: 2000
        limit-respondents: False
    hierarchical-nocovariates-covariances:
        n-tune: 6000
        n-draws:
            prior: 1000
            posterior: 2000
        limit-respondents: 1000
        runtime: # (min)
            prior: 60
            posterior: 2880
            prediction: 60
        mem_mb:
            prior: 16000
            posterior: 46000
            prediction: 16000
    hierarchical-nocovariates-nocovariances:
        n-tune: 2000
        n-draws:
            prior: 1000
            posterior: 2000
        limit-respondents: 1000
        runtime: # (min)
            prior: 10
            posterior: 360
            prediction: 10
        mem_mb:
            prior: 8000
            posterior: 48000
            prediction: 8000
    hierarchical-covariates-nocovariances:
        n-tune: 2000
        n-draws:
            prior: 1000
            posterior: 2000
        limit-respondents: 1000
        runtime: # (min)
            prior: 10
            posterior: 360
            prediction: 10
        mem_mb:
            prior: 8000
            posterior: 48000
            prediction: 8000
    hierarchical-mrp:
        n-tune: 2000
        n-draws:
            prior: 1000
            posterior: 2000
        limit-respondents: 1000
        runtime: # (min)
            prior: 60
            posterior: 240
            prediction: 60
        mem_mb:
            prior: 16000
            posterior: 24000
            prediction: 16000
    hierarchical-mrp3:
        n-tune: 2000
        n-draws:
            prior: 1000
            posterior: 2000
        limit-respondents: 1000
        runtime: # (min)
            prior: 60
            posterior: 240
            prediction: 60
        mem_mb:
            prior: 16000
            posterior: 24000
            prediction: 16000
